### ISSUE TITLE
Cannot change controls in Harley Davidson

### ISSUE THREAD

**Issue by arcadesfan** [lindbergh-loader/lindbergh-loader#22] opened 2024-10-02 01:58 UTC
Hello

I am running the game "Harley Davidson King of the Road" using the Lindbergh-Loader on Ubuntu 22.04.

The game works fine, but the controls are tricky.

I can only drive the bikes with the mouse, which is activated by default, while I would like to use the arrow keys of the keyboard or a  gamepad instead.

It´s very difficult to control the bikes with the mouse. 

Can anyone, please, let me know how to configure the file "lindbergh.conf" so as to disable the mouse, and play the game using the keyboard or a gamepad ?

Any help will be welcome, thanks in advance !

**Comment by bobbydilley** [comment] 2024-12-19 22:13
New controller options will be released in a few days.

**Comment by bobbydilley** [comment] 2024-12-23 15:41
Please try again with new release, and create a new issue if the problem isn't fixed!

**Closed by bobbydilley** 2024-12-23 15:41 UTC

**Comment by arcadesfan** [comment] 2024-12-24 08:14
> Please try again with new release, and create a new issue if the problem isn't fixed!

Glad the new version is on the way ! But I cannot find any link to download. Where is the version 2 release published ?

I will be very grateful for your answer.

**Comment by bobbydilley** [comment] 2024-12-29 22:03
Closed as you've said that you've managed to solve in another issue.
